In [76]:
import zipfile
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [77]:
#um_df = pd.read_csv("/Users/justinmasters/Documents/DA_prereq_Justin_Masters/Notebooks/Age_and_Endurance/Data/TWO_CENTURIES_OF_UM_RACES.csv")
#um_df.head()

In [78]:
# um_df.info()

In [79]:
# um_df = um_df[um_df['Year of event'] >= 2016]

In [80]:
# um_df.info()

In [81]:
# um_df.isnull().sum()

In [82]:
# um_df[um_df.isnull().any(axis=1)]

In [83]:
# um_df = um_df.dropna()

In [84]:
# um_df.isnull().sum()

In [85]:
# um_df.info()

In [86]:
# um_df['Event dates'].unique()

In [87]:
# um_df = um_df[um_df['Event dates'] >= '08-31-206']

In [88]:
# um_df['Event dates'].unique()

In [89]:
# um_df.tail()

In [90]:
# months_in_um = um_df['Event dates'].tolist
# months_in_um

In [91]:
# convert to datetime

# um_df['Event dates'] = pd.to_datetime(um_df['Event dates'], format= '%d.%m.%Y', errors='coerce')

In [92]:
# um_df['Event dates'].dt.month.unique()

In [93]:
# um_df['Event dates'].head(20)

In [94]:
# um_df.info()

In [95]:
# um_df = um_df[um_df['Event dates'].dt.month >= 9].reset_index(drop=True)

In [96]:
 # um_df['Event dates'].dt.month.unique()

In [97]:
# um_df.info()

In [98]:
# um_df.to_csv('Results_um.csv', index=False)

In [99]:
# um_df.tail()

In [100]:
um_df = pd.read_csv("../Data/Results_um.csv")
um_df.head()

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,19:41:51 h,Team GG,RSA,1985.0,M,M23,5.381,266403
1,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,19:41:58 h,Team GG,GBR,1986.0,M,M23,5.381,266404
2,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,24:10:02 h,MAD Pat'S Brigade,GBR,1972.0,M,M45,4.386,266406
3,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,24:10:07 h,MAD Pat'S Brigade,GBR,1959.0,F,W55,4.386,266407
4,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,24:16:08 h,MAD Pat'S Brigade,GBR,1962.0,M,M55,4.368,266409

In [101]:
um_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 341390 entries, 0 to 341389
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Year of event              341390 non-null  int64
 1   Event dates                341390 non-null  object
 2   Event name                 341390 non-null  object
 3   Event distance/length      341390 non-null  object
 4   Event number of finishers  341390 non-null  int64
 5   Athlete performance        341390 non-null  object
 6   Athlete club               341390 non-null  object
 7   Athlete country            341390 non-null  object
 8   Athlete year of birth      341390 non-null  float64
 9   Athlete gender             341390 non-null  object
 10  Athlete age category       341390 non-null  object
 11  Athlete average speed      341390 non-null  object
 12  Athlete ID                 341390 non-null  int64
dtypes: float64(1), int64(3), object(9)
memory usage: 33.9+ MB

In [102]:
um_df['Gender category'] = um_df['Athlete age category'].str.extract(r'([A-Za-z]+)')
um_df['Age'] = um_df['Athlete age category'].str.extract(r'(\d+)').astype(int)

In [103]:
column_type = um_df['Age'].dtype
print(column_type)

int64

In [104]:
um_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 341390 entries, 0 to 341389
Data columns (total 15 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Year of event              341390 non-null  int64
 1   Event dates                341390 non-null  object
 2   Event name                 341390 non-null  object
 3   Event distance/length      341390 non-null  object
 4   Event number of finishers  341390 non-null  int64
 5   Athlete performance        341390 non-null  object
 6   Athlete club               341390 non-null  object
 7   Athlete country            341390 non-null  object
 8   Athlete year of birth      341390 non-null  float64
 9   Athlete gender             341390 non-null  object
 10  Athlete age category       341390 non-null  object
 11  Athlete average speed      341390 non-null  object
 12  Athlete ID                 341390 non-null  int64
 13  Gender category            341390 non-null  object
 14  Age                        341390 non-null  int64
dtypes: float64(1), int64(4), object(10)
memory usage: 39.1+ MB

In [105]:
um_df['Year of event'].unique()

array([2018, 2016, 2017, 2019, 2020, 2021, 2022])

In [106]:
um_df['Athlete age category'].unique()

array(['M23', 'M45', 'W55', 'M55', 'W35', 'W23', 'M50', 'M35', 'M60',
       'W45', 'M40', 'MU23', 'W40', 'M65', 'M70', 'W50', 'W60', 'W65',
       'WU23', 'M85', 'W30', 'M20', 'M30', 'W20', 'M75', 'W70', 'W75',
       'M80', 'MU20', 'M90', 'W80', 'WU20'], dtype=object)

In [107]:
um_df['Athlete year of birth'].unique()

array([1985., 1986., 1972., 1959., 1962., 1961., 1982., 1963., 1965.,
       1987., 1980., 1955., 1988., 1984., 1971., 1969., 1968., 1974.,
       1977., 1989., 1997., 1975., 1966., 1957., 1967., 1973., 1960.,
       1979., 1983., 1978., 1970., 1964., 1950., 1991., 1958., 1976.,
       1956., 1952., 1953., 1949., 1947., 1996., 1993., 1994., 1990.,
       1992., 1954., 1951., 1981., 1995., 1999., 2006., 2003., 2005.,
       1948., 2001., 1933., 1938., 1944., 1998., 2000., 1943., 1946.,
       2004., 1939., 1945., 2002., 1936., 1942., 1941., 1940., 1937.,
       1929., 1931., 1935., 1922., 1934., 2014., 2009., 2008., 2011.,
       2007., 2010.])

In [108]:
# Function to assing age catetory 
# Need to delete current Athlete age category column and rename Age column to Age Braket

def athlete_age_category(age):
    if age < 20:    
        return "U20"
    elif age >= 20 and age <= 25:
        return "21-25"
    elif age >= 25 and age < 30:
        return "25-29"
    elif age >= 30 and age < 35:
        return "30-34"
    elif age >= 35 and age < 40:
        return "35-39"
    elif age >= 40 and age < 45:
        return "40-44"
    elif age >= 45 and age < 50:
        return "45-49"
    elif age >= 50 and age < 55:
        return "50-54"
    elif age >= 55 and age < 60:
        return "55-59"
    elif age >= 60 and age < 65:
        return "60-64"
    elif age >= 65 and age < 70:
        return "65-69"
    elif age >= 70 and age < 75:
        return "70-74"
    elif age >= 75 and age < 80:
        return "75-79"
    elif age >= 80 and age < 85:
        return "80-84"
    elif age >= 85 and age < 90:
        return "55-89"
    else:
        return "90+"
    
um_df['Age'] = um_df['Age'].map(athlete_age_category)

In [ ]:
# Drop Athlete age category column

um_df = um_df.drop("Athlete age category", axis='columns')

In [111]:
# Rename Age to Age Bracket


um_df = um_df.rename(columns={'Age': 'Age Braket'})

In [113]:
# Drop Gender category

um_df = um_df.drop("Gender category", axis='columns')

In [114]:
um_df.head()

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete average speed,Athlete ID,Age Braket
0,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,19:41:51 h,Team GG,RSA,1985.0,M,5.381,266403,21-25
1,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,19:41:58 h,Team GG,GBR,1986.0,M,5.381,266404,21-25
2,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,24:10:02 h,MAD Pat'S Brigade,GBR,1972.0,M,4.386,266406,45-49
3,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,24:10:07 h,MAD Pat'S Brigade,GBR,1959.0,F,4.386,266407,55-59
4,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,24:16:08 h,MAD Pat'S Brigade,GBR,1962.0,M,4.368,266409,55-59

In [120]:
um_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 341390 entries, 0 to 341389
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Year of event              341390 non-null  int64
 1   Event dates                341390 non-null  object
 2   Event name                 341390 non-null  object
 3   Event distance/length      341390 non-null  object
 4   Event number of finishers  341390 non-null  int64
 5   Athlete performance        341390 non-null  object
 6   Athlete club               341390 non-null  object
 7   Athlete country            341390 non-null  object
 8   Athlete year of birth      341390 non-null  float64
 9   Athlete gender             341390 non-null  object
 10  Athlete average speed      341390 non-null  object
 11  Athlete ID                 341390 non-null  int64
 12  Age Braket                 341390 non-null  object
dtypes: float64(1), int64(3), object(9)
memory usage: 33.9+ MB

In [115]:
um_df['Event name'].unique()

array(['Peak District Challenge - Gold Ultra 100km (GBR)',
       'Peak District Challenge - Silver Ultra 80km (GBR)',
       'Peak District Challenge - Bronze Ultra 50km (GBR)', ...,
       'Urmensch Ultralauf (GER)', 'Estrela Ultra Trail (POR)',
       'Crater Rim Ultra 83km (NZL)'], shape=(2650,), dtype=object)

In [116]:
um_df['Event distance/length'].unique()

array(['106km', '80km', '50km', '40mi', '60km', '53km', '55km', '8h',
       '45km', '58km', '6h', '88km', '100km', '72km', '32mi', '30mi',
       '12h', '49.2km', '73km', '48km', '55.8km', '63.3km', '46km',
       '63km', '50mi', '57km', '105km', '45.2km', '105.6km', '129.8km',
       '81km', '158km/3Etappen', '45.4km', '48.5km', '45.1km', '45.5km',
       '46.6km', '35mi', '52km', '51.4km', '56km', '55.7km', '47km',
       '9:11h', '88km/2Etappen', '64km', '75km', '45mi', '85km', '65km',
       '45.8km', '370km/8Etappen', '112km', '52.4mi', '51mi', '34mi',
       '49km', '78km', '54km', '51km', '52.6km', '69km', '65.8km', '33mi',
       '61km', '63.6km', '101km', '64.6km', '55mi', '9h', '62km', '70km',
       '57.8km', '76km', '118km', '54.4km', '84km', '90km', '52mi',
       '50.9km', '103km', '60.2km', '103.5km', '173km/4Etappen', '11:43h',
       '45.18km', '57.2km', '67km', '24h', '67.4km', '85.6km', '132km',
       '97km', '47.6km', '110km', '66km', '15h', '51.5km', '83km',
       '102.5km', '50.3km', '36.8mi', '55.5km', '7:30h', '59km', '71.7km',
       '120.6km', '48.9km', '82km', '72.5km', '80.9km', '162.1km',
       '128km', '28mi', '6:33h', '102km', '56.4km', '57.7km', '50.5km',
       '75.5km', '52.7km', '32h', '38mi', '28.2mi', '52.5mi', '53mi',
       '100mi', '79km', '74km', '61.7km', '50.7km', '53.5km', '64.5km',
       '45.6km', '94.5km', '65.3km', '41mi', '57.6km', '60.9km', '45.3km',
       '59.7km', '51.1km', '65.7km', '99km/3Etappen', '131km', '56.8km',
       '52.5km', '7:33h', '14h', '160km', '111km', '52.9km', '170km',
       '53.1km', '56.7km', '8d', '99km', '49.5km', '93km', '120km',
       '71km', '59.8km', '126.8km', '168km', '200km', '150km', '67.3km',
       '102.5mi', '68km', '86km/2Etappen', '50K', '109km', '125km',
       '64.2km', '108.6km', '102.9km', '127.6km', '7h', '47mi', '71.6km',
       '51.8km', '16h', '70.8km', '61.8km', '71.4km', '84.3km', '54mi',
       '130km', '48h', '6d', '7d', '1000km', '53.4mi', '33.9mi', '52.3km',
       '28h', '66.54km', '69.3km', '98.4km', '104.4km', '50.0km', '95km',
       '90.8km', '115km', '48.2km', '46.7km', '36h', '84.8km', '77km',
       '62mi', '56.9km', '65.6km', '122km', '127.2km', '47.8km',
       '128.8km', '204km', '48mi', '46.5km', '41h', '180km', '166km',
       '108km', '47.4km', '18h', '50.4km', '67.9km', '61.2km', '81.6km',
       '105.5km', '84.4km', '46.4km', '52.4km', '79.9km', '61.1km',
       '50.6km', '110Km', '4h', '85km/2Etappen', '76.8km', '53.3km',
       '152km/2Etappen', '50.2km', '66.4km', '89km', '74.9km', '31.2mi',
       '49.6mi', '48.7km', '51.7km', '19:08h', '21h', '183km', '94km',
       '58mi', '10h', '19h', '49.9km', '47.9km', '81.7km', '37.5mi',
       '49.8km', '51.3km', '46.8km', '57.1km', '59.2km', '48.3km',
       '83.2km', '129.6km', '77.9km', '67.5km', '87.0km', '78.8km',
       '161km/3Etappen', '82.4km', '68.2km', '46.9km', '90.9km',
       '167.5km', '100.2km', '29h', '140km', '53Km', '56.5km', '70.7km',
       '64h', '54.6km', '55.6km', '31mi', '70.4km', '63.5km', '94.3km',
       '116km', '55.3km', '78.7km', '07:35', '96km', '104km', '127km',
       '172km', '176km', '60.7km', '119.0km', '37h', '64.4km', '63.1km',
       '64.7km', '143km', '42mi', '63.8km', '108.5km', '54.5km',
       '107km/2Etappen', '26h', '96.5km', '25h', '58h', '200mi', '71.2km',
       '46h', '56mi', '44.4mi', '38h', '69.4km', '46.2km', '80.7km',
       '58.2km', '86km', '63.25km', '36mi', '39mi', '56.6km', '31h',
       '72.3km', '64.3km', '59.3km', '117km', '100Km', '133km', '69.1km',
       '11h', '212km', '33h', '65.5km', '47.1mi', '84.2km', '33.5mi',
       '90km/2Etappen', '115km/2Etappen', '48.4km', '43h', '66.9km',
       '50h', '75mi', '165km', '62.9km', '46.1km', '20h', '23h', '105mi',
       '36.6mi', '49.6km', '80.6km', '30h', '5h', '35.5Miles', '66.3km',
       '106.5km', '6h,5h,4h'], dtype=object)

In [ ]:
# Calculate avg age per race

In [ ]:
# Graph avg age per race