In [3]:
import zipfile
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'pandas'

In [ ]:
um_df = pd.read_csv("../Data/TWO_CENTURIES_OF_UM_RACES.csv")
um_df.head()

/var/folders/77/qj38nbbs3bq7mscbtmmv1lzw0000gn/T/ipykernel_58237/2808952886.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  um_df = pd.read_csv("../Data/TWO_CENTURIES_OF_UM_RACES.csv")

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,06.01.2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,06.01.2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,06.01.2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,06.01.2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4

In [ ]:
um_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7461195 entries, 0 to 7461194
Data columns (total 13 columns):
 #   Column                     Dtype
---  ------                     -----
 0   Year of event              int64
 1   Event dates                object
 2   Event name                 object
 3   Event distance/length      object
 4   Event number of finishers  int64
 5   Athlete performance        object
 6   Athlete club               object
 7   Athlete country            object
 8   Athlete year of birth      float64
 9   Athlete gender             object
 10  Athlete age category       object
 11  Athlete average speed      object
 12  Athlete ID                 int64
dtypes: float64(1), int64(3), object(9)
memory usage: 740.0+ MB

In [ ]:
um_df = um_df[um_df['Year of event'] >= 2016]

In [ ]:
um_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3609806 entries, 0 to 3609805
Data columns (total 13 columns):
 #   Column                     Dtype
---  ------                     -----
 0   Year of event              int64
 1   Event dates                object
 2   Event name                 object
 3   Event distance/length      object
 4   Event number of finishers  int64
 5   Athlete performance        object
 6   Athlete club               object
 7   Athlete country            object
 8   Athlete year of birth      float64
 9   Athlete gender             object
 10  Athlete age category       object
 11  Athlete average speed      object
 12  Athlete ID                 int64
dtypes: float64(1), int64(3), object(9)
memory usage: 385.6+ MB

In [ ]:
um_df.isnull().sum()

Year of event                      0
Event dates                        0
Event name                         0
Event distance/length            563
Event number of finishers          0
Athlete performance                0
Athlete club                 1515502
Athlete country                    1
Athlete year of birth         255368
Athlete gender                     1
Athlete age category          254048
Athlete average speed             56
Athlete ID                         0
dtype: int64

In [ ]:
um_df[um_df.isnull().any(axis=1)]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
5,2018,06.01.2018,Selva Costera (CHI),50km,22,6:25:01 h,NaN,ARG,1974.0,M,M40,7.792,5
11,2018,06.01.2018,Selva Costera (CHI),50km,22,7:09:58 h,Rocoto Team,CHI,NaN,M,NaN,6.977,11
16,2018,06.01.2018,Selva Costera (CHI),50km,22,8:00:56 h,NaN,CHI,1971.0,M,M45,6.238,16
19,2018,06.01.2018,Selva Costera (CHI),50km,22,8:13:16 h,Santiago Mountain Runn...,CHI,NaN,M,NaN,6.082,19
20,2018,06.01.2018,Selva Costera (CHI),50km,22,8:13:28 h,MEF Ularunners,CHI,NaN,M,NaN,6.079,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3609767,2022,16.10.2022,Crater Rim Ultra 83km (NZL),83km,21,13:42:34 h,NaN,NZL,NaN,M,NaN,6.054,1044732
3609768,2022,16.10.2022,Crater Rim Ultra 83km (NZL),83km,21,13:55:09 h,NaN,NZL,NaN,M,NaN,5.963,1044733
3609769,2022,16.10.2022,Crater Rim Ultra 83km (NZL),83km,21,14:00:10 h,NaN,NZL,1994.0,M,M23,5.927,935282
3609770,2022,16.10.2022,Crater Rim Ultra 83km (NZL),83km,21,14:11:46 h,NaN,NZL,NaN,F,NaN,5.847,977490
3609771,2022,16.10.2022,Tussey Mountainback 50 Miler (USA),50mi,35,7:07:38 h,NaN,USA,1988.0,M,M23,11.29,852361

In [ ]:
um_df = um_df.dropna()

In [ ]:
um_df.isnull().sum()

Year of event                0
Event dates                  0
Event name                   0
Event distance/length        0
Event number of finishers    0
Athlete performance          0
Athlete club                 0
Athlete country              0
Athlete year of birth        0
Athlete gender               0
Athlete age category         0
Athlete average speed        0
Athlete ID                   0
dtype: int64

In [ ]:
um_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2016793 entries, 0 to 3609805
Data columns (total 13 columns):
 #   Column                     Dtype
---  ------                     -----
 0   Year of event              int64
 1   Event dates                object
 2   Event name                 object
 3   Event distance/length      object
 4   Event number of finishers  int64
 5   Athlete performance        object
 6   Athlete club               object
 7   Athlete country            object
 8   Athlete year of birth      float64
 9   Athlete gender             object
 10  Athlete age category       object
 11  Athlete average speed      object
 12  Athlete ID                 int64
dtypes: float64(1), int64(3), object(9)
memory usage: 215.4+ MB

In [ ]:
um_df['Event dates'].unique()

array(['06.01.2018', '05.01.2018', '05.-06.01.2018', ...,
       '21.-22.10.2022', '20.-23.10.2022', '16.-17.10.2022'],
      shape=(2956,), dtype=object)

In [ ]:
um_df = um_df[um_df['Event dates'] >= '08-31-206']

In [ ]:
um_df['Event dates'].unique()

array(['24.03.2018', '24.-25.03.2018', '23.-25.03.2018', ...,
       '21.-22.10.2022', '20.-23.10.2022', '16.-17.10.2022'],
      shape=(2251,), dtype=object)

In [ ]:
um_df.tail()

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
3609801,2022,16.10.2022,Tussey Mountainback 50 Miler (USA),50mi,35,11:16:08 h,"*Peachtree City, GA",USA,1968.0,M,M50,7.141,1044739
3609802,2022,16.10.2022,Tussey Mountainback 50 Miler (USA),50mi,35,11:27:05 h,"*Newport, PA",USA,1959.0,M,M60,7.027,50971
3609803,2022,16.10.2022,Tussey Mountainback 50 Miler (USA),50mi,35,11:46:34 h,"*Flemington, NJ",USA,1955.0,F,W65,6.833,73152
3609804,2022,16.10.2022,Tussey Mountainback 50 Miler (USA),50mi,35,11:55:29 h,"*Arlington, VA",USA,1965.0,M,M55,6.748,970133
3609805,2022,16.10.2022,Tussey Mountainback 50 Miler (USA),50mi,35,12:14:15 h,"*Johnstown, PA",USA,1981.0,F,W40,6.575,723380

In [ ]:
months_in_um = um_df['Event dates'].tolist
months_in_um

<bound method IndexOpsMixin.tolist of 665        24.03.2018
666        24.03.2018
667        24.03.2018
668        24.03.2018
669        24.03.2018
              ...
3609801    16.10.2022
3609802    16.10.2022
3609803    16.10.2022
3609804    16.10.2022
3609805    16.10.2022
Name: Event dates, Length: 1586627, dtype: object>

In [ ]:
# convert to datetime

um_df['Event dates'] = pd.to_datetime(um_df['Event dates'], format= '%d.%m.%Y', errors='coerce')

In [ ]:
um_df['Event dates'].dt.month.unique()

array([ 3., nan,  2.,  1.,  4.,  6.,  5.,  7.,  9.,  8., 10., 12., 11.])

In [ ]:
um_df['Event dates'].head(20)

665   2018-03-24
666   2018-03-24
667   2018-03-24
668   2018-03-24
669   2018-03-24
670   2018-03-24
671   2018-03-24
674   2018-03-24
675   2018-03-24
676   2018-03-24
677   2018-03-24
678   2018-03-24
680   2018-03-24
681   2018-03-24
682   2018-03-24
683   2018-03-24
684   2018-03-24
687   2018-03-24
688   2018-03-24
689   2018-03-24
Name: Event dates, dtype: datetime64[ns]

In [ ]:
um_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1586627 entries, 665 to 3609805
Data columns (total 13 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Year of event              1586627 non-null  int64
 1   Event dates                1237586 non-null  datetime64[ns]
 2   Event name                 1586627 non-null  object
 3   Event distance/length      1586627 non-null  object
 4   Event number of finishers  1586627 non-null  int64
 5   Athlete performance        1586627 non-null  object
 6   Athlete club               1586627 non-null  object
 7   Athlete country            1586627 non-null  object
 8   Athlete year of birth      1586627 non-null  float64
 9   Athlete gender             1586627 non-null  object
 10  Athlete age category       1586627 non-null  object
 11  Athlete average speed      1586627 non-null  object
 12  Athlete ID                 1586627 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(8)
memory usage: 169.5+ MB

In [ ]:
um_df = um_df[um_df['Event dates'].dt.month >= 9].reset_index(drop=True)

In [ ]:
um_df['Event dates'].dt.month.unique()

array([ 9, 10, 12, 11], dtype=int32)

In [ ]:
um_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 341390 entries, 0 to 341389
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Year of event              341390 non-null  int64
 1   Event dates                341390 non-null  datetime64[ns]
 2   Event name                 341390 non-null  object
 3   Event distance/length      341390 non-null  object
 4   Event number of finishers  341390 non-null  int64
 5   Athlete performance        341390 non-null  object
 6   Athlete club               341390 non-null  object
 7   Athlete country            341390 non-null  object
 8   Athlete year of birth      341390 non-null  float64
 9   Athlete gender             341390 non-null  object
 10  Athlete age category       341390 non-null  object
 11  Athlete average speed      341390 non-null  object
 12  Athlete ID                 341390 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(8)
memory usage: 33.9+ MB

In [ ]:
um_df.to_csv('Results_um.csv', index=False)

In [ ]:
um_df.tail()

In [ ]:
um_df = pd.read_csv("../Data/Results_um.csv")
um_df.head()

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete average speed,Athlete ID,Age Braket
0,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,19:41:51 h,Team GG,RSA,1985.0,M,5.381,266403,21-25
1,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,19:41:58 h,Team GG,GBR,1986.0,M,5.381,266404,21-25
2,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,24:10:02 h,MAD Pat'S Brigade,GBR,1972.0,M,4.386,266406,45-49
3,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,24:10:07 h,MAD Pat'S Brigade,GBR,1959.0,F,4.386,266407,55-59
4,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,24:16:08 h,MAD Pat'S Brigade,GBR,1962.0,M,4.368,266409,55-59

In [ ]:
um_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 341390 entries, 0 to 341389
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Year of event              341390 non-null  int64
 1   Event dates                341390 non-null  object
 2   Event name                 341390 non-null  object
 3   Event distance/length      341390 non-null  object
 4   Event number of finishers  341390 non-null  int64
 5   Athlete performance        341390 non-null  object
 6   Athlete club               341390 non-null  object
 7   Athlete country            341390 non-null  object
 8   Athlete year of birth      341390 non-null  float64
 9   Athlete gender             341390 non-null  object
 10  Athlete average speed      341390 non-null  object
 11  Athlete ID                 341390 non-null  int64
 12  Age Braket                 341390 non-null  object
dtypes: float64(1), int64(3), object(9)
memory usage: 33.9+ MB

In [ ]:
um_df['Gender category'] = um_df['Athlete age category'].str.extract(r'([A-Za-z]+)')
um_df['Age'] = um_df['Athlete age category'].str.extract(r'(\d+)').astype(int)

In [ ]:
# column_type = um_df['Age'].dtype
# print(column_type)

In [ ]:
um_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 341390 entries, 0 to 341389
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Year of event              341390 non-null  int64
 1   Event dates                341390 non-null  object
 2   Event name                 341390 non-null  object
 3   Event distance/length      341390 non-null  object
 4   Event number of finishers  341390 non-null  int64
 5   Athlete performance        341390 non-null  object
 6   Athlete club               341390 non-null  object
 7   Athlete country            341390 non-null  object
 8   Athlete year of birth      341390 non-null  float64
 9   Athlete gender             341390 non-null  object
 10  Athlete average speed      341390 non-null  object
 11  Athlete ID                 341390 non-null  int64
 12  Age Braket                 341390 non-null  object
dtypes: float64(1), int64(3), object(9)
memory usage: 33.9+ MB

In [ ]:
um_df['Year of event'].unique()

array([2018, 2016, 2017, 2019, 2020, 2021, 2022])

In [ ]:
um_df['Athlete age category'].unique()

array(['M23', 'M45', 'W55', 'M55', 'W35', 'W23', 'M50', 'M35', 'M60',
       'W45', 'M40', 'MU23', 'W40', 'M65', 'M70', 'W50', 'W60', 'W65',
       'WU23', 'M85', 'W30', 'M20', 'M30', 'W20', 'M75', 'W70', 'W75',
       'M80', 'MU20', 'M90', 'W80', 'WU20'], dtype=object)

In [ ]:
um_df['Athlete year of birth'].unique()

array([1985., 1986., 1972., 1959., 1962., 1961., 1982., 1963., 1965.,
       1987., 1980., 1955., 1988., 1984., 1971., 1969., 1968., 1974.,
       1977., 1989., 1997., 1975., 1966., 1957., 1967., 1973., 1960.,
       1979., 1983., 1978., 1970., 1964., 1950., 1991., 1958., 1976.,
       1956., 1952., 1953., 1949., 1947., 1996., 1993., 1994., 1990.,
       1992., 1954., 1951., 1981., 1995., 1999., 2006., 2003., 2005.,
       1948., 2001., 1933., 1938., 1944., 1998., 2000., 1943., 1946.,
       2004., 1939., 1945., 2002., 1936., 1942., 1941., 1940., 1937.,
       1929., 1931., 1935., 1922., 1934., 2014., 2009., 2008., 2011.,
       2007., 2010.])

In [ ]:
um_df = um_df.rename(columns={'Age Braket': 'Age Bracket'})

In [ ]:
um_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 341390 entries, 0 to 341389
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Year of event              341390 non-null  int64
 1   Event dates                341390 non-null  object
 2   Event name                 341390 non-null  object
 3   Event distance/length      341390 non-null  object
 4   Event number of finishers  341390 non-null  int64
 5   Athlete performance        341390 non-null  object
 6   Athlete club               341390 non-null  object
 7   Athlete country            341390 non-null  object
 8   Athlete year of birth      341390 non-null  float64
 9   Athlete gender             341390 non-null  object
 10  Athlete average speed      341390 non-null  object
 11  Athlete ID                 341390 non-null  int64
 12  Age Bracket                341390 non-null  object
dtypes: float64(1), int64(3), object(9)
memory usage: 33.9+ MB

In [ ]:
# Function to assing age catetory 
# Need to delete current Athlete age category column and rename Age column to Age Braket

def athlete_age_category(age):
    if age < 20:    
        return "U20"
    elif age >= 20 and age <= 25:
        return "21-25"
    elif age >= 25 and age < 30:
        return "25-29"
    elif age >= 30 and age < 35:
        return "30-34"
    elif age >= 35 and age < 40:
        return "35-39"
    elif age >= 40 and age < 45:
        return "40-44"
    elif age >= 45 and age < 50:
        return "45-49"
    elif age >= 50 and age < 55:
        return "50-54"
    elif age >= 55 and age < 60:
        return "55-59"
    elif age >= 60 and age < 65:
        return "60-64"
    elif age >= 65 and age < 70:
        return "65-69"
    elif age >= 70 and age < 75:
        return "70-74"
    elif age >= 75 and age < 80:
        return "75-79"
    elif age >= 80 and age < 85:
        return "80-84"
    elif age >= 85 and age < 90:
        return "55-89"
    else:
        return "90+"
    
um_df['Age'] = um_df['Age'].map(athlete_age_category)

In [ ]:
# Drop Athlete age category column

um_df = um_df.drop("Athlete age category", axis='columns')

In [ ]:
# Rename Age to Age Bracket


um_df = um_df.rename(columns={'Age': 'Age Bracket'})

In [ ]:
# Drop Gender category

um_df = um_df.drop("Gender category", axis='columns')

In [ ]:
um_df.head()

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete average speed,Athlete ID,Age Braket
0,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,19:41:51 h,Team GG,RSA,1985.0,M,5.381,266403,21-25
1,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,19:41:58 h,Team GG,GBR,1986.0,M,5.381,266404,21-25
2,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,24:10:02 h,MAD Pat'S Brigade,GBR,1972.0,M,4.386,266406,45-49
3,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,24:10:07 h,MAD Pat'S Brigade,GBR,1959.0,F,4.386,266407,55-59
4,2018,2018-09-21,Peak District Challenge - Gold Ultra 100km (GBR),106km,11,24:16:08 h,MAD Pat'S Brigade,GBR,1962.0,M,4.368,266409,55-59

In [ ]:
um_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 341390 entries, 0 to 341389
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Year of event              341390 non-null  int64
 1   Event dates                341390 non-null  object
 2   Event name                 341390 non-null  object
 3   Event distance/length      341390 non-null  object
 4   Event number of finishers  341390 non-null  int64
 5   Athlete performance        341390 non-null  object
 6   Athlete club               341390 non-null  object
 7   Athlete country            341390 non-null  object
 8   Athlete year of birth      341390 non-null  float64
 9   Athlete gender             341390 non-null  object
 10  Athlete average speed      341390 non-null  object
 11  Athlete ID                 341390 non-null  int64
 12  Age Bracket                341390 non-null  object
dtypes: float64(1), int64(3), object(9)
memory usage: 33.9+ MB

In [ ]:
um_df['Event name'].unique()

array(['Peak District Challenge - Gold Ultra 100km (GBR)',
       'Peak District Challenge - Silver Ultra 80km (GBR)',
       'Peak District Challenge - Bronze Ultra 50km (GBR)', ...,
       'Urmensch Ultralauf (GER)', 'Estrela Ultra Trail (POR)',
       'Crater Rim Ultra 83km (NZL)'], shape=(2650,), dtype=object)

In [ ]:
um_df['Event distance/length'].unique()

array(['106km', '80km', '50km', '40mi', '60km', '53km', '55km', '8h',
       '45km', '58km', '6h', '88km', '100km', '72km', '32mi', '30mi',
       '12h', '49.2km', '73km', '48km', '55.8km', '63.3km', '46km',
       '63km', '50mi', '57km', '105km', '45.2km', '105.6km', '129.8km',
       '81km', '158km/3Etappen', '45.4km', '48.5km', '45.1km', '45.5km',
       '46.6km', '35mi', '52km', '51.4km', '56km', '55.7km', '47km',
       '9:11h', '88km/2Etappen', '64km', '75km', '45mi', '85km', '65km',
       '45.8km', '370km/8Etappen', '112km', '52.4mi', '51mi', '34mi',
       '49km', '78km', '54km', '51km', '52.6km', '69km', '65.8km', '33mi',
       '61km', '63.6km', '101km', '64.6km', '55mi', '9h', '62km', '70km',
       '57.8km', '76km', '118km', '54.4km', '84km', '90km', '52mi',
       '50.9km', '103km', '60.2km', '103.5km', '173km/4Etappen', '11:43h',
       '45.18km', '57.2km', '67km', '24h', '67.4km', '85.6km', '132km',
       '97km', '47.6km', '110km', '66km', '15h', '51.5km', '83km',
       '102.5km', '50.3km', '36.8mi', '55.5km', '7:30h', '59km', '71.7km',
       '120.6km', '48.9km', '82km', '72.5km', '80.9km', '162.1km',
       '128km', '28mi', '6:33h', '102km', '56.4km', '57.7km', '50.5km',
       '75.5km', '52.7km', '32h', '38mi', '28.2mi', '52.5mi', '53mi',
       '100mi', '79km', '74km', '61.7km', '50.7km', '53.5km', '64.5km',
       '45.6km', '94.5km', '65.3km', '41mi', '57.6km', '60.9km', '45.3km',
       '59.7km', '51.1km', '65.7km', '99km/3Etappen', '131km', '56.8km',
       '52.5km', '7:33h', '14h', '160km', '111km', '52.9km', '170km',
       '53.1km', '56.7km', '8d', '99km', '49.5km', '93km', '120km',
       '71km', '59.8km', '126.8km', '168km', '200km', '150km', '67.3km',
       '102.5mi', '68km', '86km/2Etappen', '50K', '109km', '125km',
       '64.2km', '108.6km', '102.9km', '127.6km', '7h', '47mi', '71.6km',
       '51.8km', '16h', '70.8km', '61.8km', '71.4km', '84.3km', '54mi',
       '130km', '48h', '6d', '7d', '1000km', '53.4mi', '33.9mi', '52.3km',
       '28h', '66.54km', '69.3km', '98.4km', '104.4km', '50.0km', '95km',
       '90.8km', '115km', '48.2km', '46.7km', '36h', '84.8km', '77km',
       '62mi', '56.9km', '65.6km', '122km', '127.2km', '47.8km',
       '128.8km', '204km', '48mi', '46.5km', '41h', '180km', '166km',
       '108km', '47.4km', '18h', '50.4km', '67.9km', '61.2km', '81.6km',
       '105.5km', '84.4km', '46.4km', '52.4km', '79.9km', '61.1km',
       '50.6km', '110Km', '4h', '85km/2Etappen', '76.8km', '53.3km',
       '152km/2Etappen', '50.2km', '66.4km', '89km', '74.9km', '31.2mi',
       '49.6mi', '48.7km', '51.7km', '19:08h', '21h', '183km', '94km',
       '58mi', '10h', '19h', '49.9km', '47.9km', '81.7km', '37.5mi',
       '49.8km', '51.3km', '46.8km', '57.1km', '59.2km', '48.3km',
       '83.2km', '129.6km', '77.9km', '67.5km', '87.0km', '78.8km',
       '161km/3Etappen', '82.4km', '68.2km', '46.9km', '90.9km',
       '167.5km', '100.2km', '29h', '140km', '53Km', '56.5km', '70.7km',
       '64h', '54.6km', '55.6km', '31mi', '70.4km', '63.5km', '94.3km',
       '116km', '55.3km', '78.7km', '07:35', '96km', '104km', '127km',
       '172km', '176km', '60.7km', '119.0km', '37h', '64.4km', '63.1km',
       '64.7km', '143km', '42mi', '63.8km', '108.5km', '54.5km',
       '107km/2Etappen', '26h', '96.5km', '25h', '58h', '200mi', '71.2km',
       '46h', '56mi', '44.4mi', '38h', '69.4km', '46.2km', '80.7km',
       '58.2km', '86km', '63.25km', '36mi', '39mi', '56.6km', '31h',
       '72.3km', '64.3km', '59.3km', '117km', '100Km', '133km', '69.1km',
       '11h', '212km', '33h', '65.5km', '47.1mi', '84.2km', '33.5mi',
       '90km/2Etappen', '115km/2Etappen', '48.4km', '43h', '66.9km',
       '50h', '75mi', '165km', '62.9km', '46.1km', '20h', '23h', '105mi',
       '36.6mi', '49.6km', '80.6km', '30h', '5h', '35.5Miles', '66.3km',
       '106.5km', '6h,5h,4h'], dtype=object)

In [ ]:
um_df.to_csv('Results_um1.csv', index=False)

In [ ]:
# Calculate avg age per race

In [ ]:
# Graph avg age per race